apernet/hysteria

README.md
README.zh.md
cmd/proxy_client.go
cmd/proxy_config.go
cmd/proxy_server.go
cmd/relay_client.go
pkg/socks5/server.go

Add disable UDP option for both proxy client & server

---

README.md
README.zh.md
cmd/main.go

Add log level & format environment variables

---

cmd/proxy_client.go
cmd/proxy_config.go
pkg/http/server.go

add http basic auth
ref tobyxdd/hysteria#15

feat(client): add http basic auth

---

cmd/main.go

feat(log): add log timestamp format

---

cmd/proxy_client.go
cmd/proxy_config.go
go.mod
pkg/http/server.go

support https proxy
use the built-in basic auth extension
ref tobyxdd/hysteria#14 tobyxdd/hysteria#15

feat(client): support https proxy

---

cmd/proxy_client.go
cmd/proxy_config.go

SOCKS5 username & password auth option

---

.github/workflows/release.yml

fix: https://github.com/tobyxdd/hysteria/issues/34

ensure static-linked

---

pkg/core/client.go
pkg/core/obfs.go
pkg/core/server.go

Passthrough required methods for quic-go to increase the buffer size

---

README.md
README.zh.md
cmd/server.go
pkg/auth/http.go

HTTP external auth implementation

---

.github/workflows/docker.yaml
Dockerfile

update dockerfile
add ci support

chore(docker): update dockerfile

---

pkg/acl/engine.go
pkg/acl/engine_test.go
pkg/acl/entry.go
pkg/acl/ip.go
pkg/core/client.go
pkg/core/protocol.go
pkg/core/server.go
pkg/core/server_client.go
pkg/http/server.go
pkg/socks5/server.go

Protocol 2.0

---

cmd/client.go
cmd/server.go
pkg/acl/engine.go
pkg/acl/engine_test.go
pkg/acl/entry.go
pkg/acl/ip.go
pkg/core/client.go
pkg/core/obfs.go
pkg/core/protocol.go
pkg/core/server.go
pkg/core/server_client.go
pkg/http/server.go
pkg/obfs/xor.go
pkg/obfs/xplus.go
pkg/obfs/xplus_test.go
pkg/socks5/server.go
pkg/utils/df_linux.go
pkg/utils/df_stub.go
pkg/utils/df_windows.go

Better obfs

---

README.md
README.zh.md
pkg/core/server.go
pkg/core/server_client.go

Prometheus Active Conn Gauge

---

cmd/main.go
cmd/update.go
go.mod
go.sum

Better CLI

---

README.md
README.zh.md
cmd/client.go
cmd/config.go

Add TLS server name option for client

---

README.md
README.zh.md
cmd/client.go
cmd/config.go
cmd/server.go
go.mod

Option to disable MTU discovery

---

Docker.md
Docker.zh.md
README.md
README.zh.md
docker-compose.yaml

docs(docker): add docker docs

---

README.md
README.zh.md
cmd/client.go
pkg/tproxy/tcp_linux.go
pkg/tproxy/tcp_stub.go
pkg/tproxy/udp_linux.go
pkg/tproxy/udp_stub.go
pkg/tun/server.go
pkg/tun/server_stub.go
pkg/tun/tcp.go
pkg/tun/udp.go

Remove ACL from TPROXY & TUN

---

Docker.md
Docker.zh.md
Dockerfile

- add build flag
- update docker doc

chore(docker): add build flag

---

README.md
README.zh.md
cmd/client.go
cmd/config.go
cmd/server.go

Customizable ALPN

---

cmd/kploader.go
cmd/server.go

Reload server keypair every 10 minutes

---

README.md
README.zh.md

Add the document: how to generate and use CA

how to generate CA

---

README.md
README.zh.md
cmd/config.go
cmd/server.go
pkg/transport/transport.go

ipv6 only mode

---

docker-compose[Multiple_Instances].yaml

Multi-instance docker-compose, for physical servers with multiple NICs or IPs
Network:host has bug,now work all good

Multi-instance docker-compose

---

cmd/auth/cmd.go
cmd/auth/http.go
cmd/main.go
cmd/server.go

feat: multi-password & cmd auth

---

cmd/client.go
pkg/tproxy/udp_linux.go

fix: incorrect TProxy UDP implementation 

---

go.mod
go.sum
pkg/core/client.go
pkg/core/frag.go
pkg/core/frag_test.go
pkg/core/protocol.go
pkg/core/server_client.go

UDP fragmentation support

---

cmd/client.go
cmd/config.go
cmd/server.go
pkg/transport/client.go
pkg/transport/resolve.go
pkg/transport/server.go

feat: resolve preference

---

pkg/acl/engine.go
pkg/acl/engine_test.go
pkg/acl/entry.go
pkg/acl/entry_test.go
pkg/core/server_client.go
pkg/http/server.go
pkg/socks5/server.go

ACL protocol & port support

---

Taskfile.yaml

Add taskfile to support custom build.
Taskfile Docs: [https://taskfile.dev](https://taskfile.dev)

chore(build): add taskfile

---

cmd/client.go
cmd/config.go
pkg/redirect/tcp_linux.go
pkg/redirect/tcp_stub.go

feat: TCP redirect implementation

---

.github/workflows/build-master.yml
.github/workflows/release.yml
Dockerfile
cmd/client.go
cmd/resolver.go
cmd/server.go
go.mod
go.sum
pkg/transport/client.go
pkg/transport/resolve.go
pkg/transport/server.go

feat: rework resolver support

---

cmd/client.go
cmd/client_gpl.go
cmd/ipmasker.go
cmd/main.go
cmd/server.go

feat: IP masks

---

Dockerfile
build.sh

chore(ci): fix docker build failed

---

Dockerfile

chore(docker): Compatible with nerdctl build

---

core/cs/frag.go
core/cs/frag_test.go

fix: handle the case where MsgID == 0

---

.gitignore
Taskfile.yaml

chore(go-task): support freebsd & windows build

---

app/cmd/main.go
app/cmd/winvt.go
app/cmd/winvt_stub.go

Enable Colorful Terminal in windows platform.

Add Win32 VT mode support

---

build.sh

Verified with go 1.20.4
For detail: https://github.com/golang/go/issues/34186

feat: reproducible building

---

app/cmd/server.go

Log requests that go to masquerade handlers, so that failed authentication/probing attempts are visible in the logs (debug level).
This would give the server admin more insight in case someone tries to brute-force the password or determine if the server is a Hysteria server, for example.

feat: log (debug) masquerade requests

---

app/cmd/server.go
app/cmd/server_test.go
app/cmd/server_test.yaml
extras/masq/server.go

Note to self: requires doc changes.

feat: HTTP/HTTPS masq servers

---

app/cmd/server.go
app/go.mod

Add ZeroSSL EAB support to fix `HTTP 400 urn:ietf:params:acme:error:externalAccountRequired` error

feat(server): add ZeroSSL EAB

---

app/cmd/server.go
app/cmd/server_test.go
app/cmd/server_test.yaml

feat: masquerade string mode

---

app/cmd/server.go
app/cmd/server_test.go
app/cmd/server_test.yaml
extras/outbounds/ob_http.go

feat: HTTP/HTTPS proxy outbound

---

app/cmd/server.go
app/cmd/server_test.go
app/cmd/server_test.yaml
app/internal/utils/geoloader.go

feat: geoUpdateInterval

---

extras/outbounds/acl/compile.go
extras/outbounds/acl/compile_test.go
extras/outbounds/acl/matchers.go
extras/outbounds/acl/matchers_test.go

feat: domain suffix match

---

app/cmd/client.go
core/client/reconnect.go

Closes https://github.com/apernet/hysteria/issues/869

fix: lazy mode should defer config evaluation

---

core/client/reconnect.go

fix: incorrect reconnect logic that causes blocking when dialing connections

---

app/internal/utils/bpsconv_test.go

test: correct TestStringToBps after `6d6a26b`

---

app/go.mod
app/go.sum
core/go.mod
core/go.sum
extras/go.mod
extras/go.sum

Closes https://github.com/apernet/hysteria/issues/958

fix: FreeBSD IPv4-mapped IPv6 listening addr fix

---

app/cmd/server.go
app/cmd/server_test.go
app/cmd/server_test.yaml
app/cmd/speedtest.go
extras/outbounds/speedtest.go
extras/outbounds/speedtest/client.go
extras/outbounds/speedtest/protocol.go
extras/outbounds/speedtest/protocol_test.go
extras/outbounds/speedtest/server.go

feat: built-in speed test client & server

---

core/internal/congestion/brutal/brutal.go

Prevent the congestion window from falling below the size of single packet in scenarios with extremely low RTT, which previously led to transmission stalls.

fix: cwnd undersize in extremely-low rtt scenarios

---

app/cmd/server.go

support acme listen host
ref #978

feat(acme): support acme listen host

---

app/cmd/client.go
app/cmd/server.go

Degrade the Inconsequential log level to avoid annoying output.

degrade the log level adjustment for tcpError and udpError

---

scripts/install_server.sh

This fixes the following error on AlmaLinux 8.9
```
[root@alpha-3cd93aefda ~]# systemctl start hysteria-server.service
Failed to start hysteria-server.service: Unit hysteria-server.service not found.
```
Ref: #1029

fix(scripts): set secontext for systemd unit

---

app/cmd/server.go

fix: check if cert-key is loadable on server start

---

scripts/install_server.sh

fix(scripts): chcon error on CentOS 7

---

app/go.mod
app/go.sum
core/go.mod
core/go.sum
extras/go.mod
extras/go.sum

fix: quic-go memory leak

---

hyperbole.py

fix(hyperbole): missing v2 in cmdpkg

---

core/server/udp_test.go

fix(test): signature mismatch of udpIO.Hook

---

extras/sniff/sniff.go
extras/sniff/sniff_test.go

fix: sniffing handled HTTP host header incorrectly

---

app/cmd/server.go
app/cmd/server_test.go
app/cmd/server_test.yaml
core/go.sum

close: #1278
masquerade.proxy.insecureSkipVerify

feat: allow skip cert verify in masquerade.proxy

---

hyperbole.py
platforms.txt
scripts/install_server.sh

Add support for loongarch64

---

app/LICENSE.md
core/LICENSE.md
extras/LICENSE.md

Closes https://github.com/apernet/hysteria/issues/1330

chore: add LICENSE to packages

---

core/internal/congestion/bbr/packet_number_indexed_queue.go
extras/trafficlogger/http.go

chore: fix function name in comment
