- pkg/tun/server.go
- pkg/tun/server_fake.go
- pkg/tun/tcp.go
- pkg/tun/udp.go
So we can build a statically linked executable and make it easier to run hysteria on the OpenWRT.
ref: https://t.me/hysteria_github/1706
ref: https://t.me/c/1455796760/28966
> Allow build with CGO_ENABLED=0 by disable TUN Mode

- Dockerfile
set up nsswitch.conf for Go's "netgo" implementation
> chore(docker): set up nsswitch.conf for Go's "netgo" implementation

- .gitignore
- README.md
- README.zh.md
- cmd/client.go
- cmd/config.go
- cmd/main.go
support multiple relays for udp and tcp, consider the compatibility, don't delete  the old  config `relay_tcp` and `relay_udp`, and also update the readme.md
> multiple relay

- install.sh
Bash script for installing Hysteria in operating systems such as Debian / CentOS / Fedora / openSUSE that support systemd. Modified from [fhs-install-v2ray](https://github.com/v2fly/fhs-install-v2ray)
出於安全性考慮，可能需要創建一個新的特定用戶`hysteria`來運行systemd服務
> Bash script for installing Hysteria with systemd

- cmd/client.go
- cmd/config.go
- cmd/server.go
- pkg/core/client.go
According to the discuss #420, some users want hysteria to exit rather than auto re-connect when the QUIC connection is interrupted.
And some related timeout options are also exposed into the config, as I think the default `MaxIdleTimeout` (30s) is too long in this use case.
p.s. I don't think the `"quic_settings"` is a great name (and it really looks like an inbound), feel free to advise if you have a better idea.
> Allow users disable the auto reconnect behavior and related timeout

- .gitignore
- cmd/client.go
- cmd/config.go
- go.mod
- go.sum
- pkg/core/client.go
Adds an option `fast_open` in client config to defer the response handling to the first Read() call, which allows applications to send requests without waiting for an RTT.
Tested using [docs/socks5/check.py](https://github.com/apernet/hysteria/blob/536fa24595c8fcf805cdd4eab47bdc8e757f386f/docs/socks5/check.py):
no `fast_open`:
```
Sending HTTP request to 1.1.1.1
Response received
Time: 206.59 ms
```
with `fast_open`:
```
Sending HTTP request to 1.1.1.1
Response received
Time: 105.87 ms
```
**Note that this breaks the semantics of the SOCKS5/HTTP proxy, as what's originally returned as a "host unreachable" error will become an "empty reply from server" error (because the proxy now always accepts a connection to "bait" for a request).**
For this reason, we should make this disabled by …
> feat: fast open

- install_server.sh
I noted there are still some users of this script. So I rewrite it to solve some historical issues and make it more user-friendly.
+ Better user interface with more colorful hints (see screenshots).
+ Correctly detecting and restarting multiple running hysteria-server systemd services after hysteria upgraded, this also fixes #513 and #514 
+ Auto re-exec with sudo when run as non-root user (supports VPS uses non-root login user, such as GCP). 
+ Better command line flags parser.
> Rewrite install_server.sh

- Taskfile.yaml
> chore(go-task): supported amd64-v* & s390x

- app/cmd/client.go
- app/cmd/config.go
- core/cs/client.go
When on, the client will not attempt to connect to the server at startup, only when a connection is initiated.
This behavior matches that of trojan, v2ray and tuic, but behind a config option for compatibility.
> Add `lazy_start` option.

- core/cs/server_client.go
- core/transport/server.go
The domain is directly forwarded to SOCKS5 outbound, so unnecessary DNS lookups can be saved when there is no ACL.
> Remove unnecessary DNS queries in case of SOCKS5 outbound

- app/cmd/client.go
- app/cmd/client_test.go
- app/cmd/client_test.yaml
- app/internal/redirect/getsockopt_linux.go
- app/internal/redirect/getsockopt_linux_386.go
- app/internal/redirect/syscall_socketcall_linux_386.s
- app/internal/redirect/tcp_linux.go
- app/internal/redirect/tcp_others.go
Add back TCP redirection mode because some users don't know how to use TPROXY and/or don't have a kernel with TPROXY support. Code is ported from Hysteria 1 with minor changes.
Example:
`iptables -t nat -A OUTPUT -p tcp -d 34.117.59.81 -j REDIRECT --to-ports 3500`
Closes https://github.com/apernet/hysteria/issues/659
Note to self: requires doc changes.
> feat: TCP redirect mode

- core/internal/protocol/proxy.go
My public hysteria2 node panicked yesterday, so I checked my log file and added slice length checking in this function.
```
Oct 19 15:56:44 ziyong hysteria[1110255]: 2023-10-19T15:56:44+08:00        ERROR        UDP error        {"addr": "x.x.x.x:58411", "id": "xxxx", "sessionID": 16912948, "error": "strconv.Atoi: parsing \"20715\\xf2\\x0f\\xf8\\x8c\\xb1$\\xe5It6\\xd9+\\\";\\x84\\x8b\\xe7 h\\xa5\\xd5Qu\\xffFpL\\xc1xNX\\x90U<\": invalid syntax"}
Oct 19 15:56:45 ziyong hysteria[1110255]: panic: runtime error: slice bounds out of range [:46] with capacity 41
Oct 19 15:56:45 ziyong hysteria[1110255]: goroutine 249844 [running]:
Oct 19 15:56:45 ziyong hysteria[1110255]: github.com/apernet/hysteria/core/internal/protocol.ParseUDPMessage({0xc0009808c0, 0x32, 0x32})
Oct 19 15:56:45 ziyong …
```
> fix: Fix slice out-of-bounds issues in ParseUDPMessage.

- app/cmd/server.go
Add hysteria listening address logging output when starting up. It would be useful to tell someone when he forgets to write 'listen' option, but the server is still running on default port 443
> Add hysteria listening address logging output when starting up

- app/cmd/client.go
- app/cmd/server.go
- extras/correctnet/correctnet.go
- extras/masq/server.go
Fix: #797
When listening on a wildcard address like `"0.0.0.0"` or `"[::]"`, hysteria actually listened on both IPv4 and IPv6. This is a well-known bug of the golang net package.
This PR introduces a fix for that, the intended behavior will be:
| Config        | Behavior                     |
|---------------|------------------------------|
| `0.0.0.0:443` | Listen on IPv4 only          |
| `[::]:443`    | Listen on IPv6 only          |
| `:443`        | Listen on both IPv4 and IPv6 |
Intentionly, I did not adopt this bug fix for `tcpTProxy`, `udpTProxy` and `tcpRedirect`, as they should always be dual stack listening.
> fix: ipv{4,6}-only listen on wildcard address

- app/go.sum
- go.work.sum
我不清楚这是不是仍旧有用的，因为这些更改可能是 #539 遗落的
> chore(go.sum): thoroughly clean up unneeded fields

- extras/outbounds/ob_socks5.go
ref: #932, socks5 error is shown in log as numeric error code.
This PR `strerror(3)` the socks5 errors from outbounds with [RFC 1928](https://datatracker.ietf.org/doc/html/rfc1928#section-6).
> chore: human-readable outbounds socks5 error msg

- app/internal/utils/geoloader.go
Close: #944 
This PR introduced 3 behaviors to work around this issue.
1. Download the GeoIP or GeoSite to a temporary file and make sure it is loadable before moving it to the destination.
2. Re-download the GeoIP or GeoSite database if it exists but cannot be loaded.
3. In the case of download failure, instead of exiting with an error, fallback to the previous download as long as it available.
> fix: fail to load GeoIP or GeoSite if previous download was interrupted by network error

- app/cmd/client.go
- extras/transport/udphop/conn.go
Third-party clients can use this to set options on underlay UDP socket. 
e.g. calling [`VpnService.protect()`](https://developer.android.com/reference/android/net/VpnService#protect(int)) on Android.
> feat: allow set ListenUDP impl for udphop conn

- extras/outbounds/acl/compile.go
- extras/outbounds/acl/compile_test.go
Enable the ProtoPort parameter to support range formats when the user inputs as follows:
```
reject(all, tcp/1022-1024)
```
It will works as 3 rules below:
```
reject(all, tcp/1022) 
reject(all, tcp/1023) 
reject(all, tcp/1024)
```
This feature is particularly beneficial for blocking a wide range of contiguous ports.
```
- reject(all, tcp/6969)
- reject(all, tcp/6881-6889)
- reject(all, tcp/10001-65535)
```
> Support range format ProtoPort

- app/go.mod
- app/go.sum
Upsteam released this yesterday for a bugfix.
Changes: https://github.com/SagerNet/sing-tun/compare/v0.2.4...v0.2.5
Note to @tobyxdd: Please merge this before the next release of Hysteria.
> chore(deps): bump sing-tun from v0.2.4 to v0.2.5

- scripts/install_server.sh
Running apt update to avoid "package not found" error on some pre-installed Ubuntu / Debian.
I have tested that other supported Linux distributions do not need this.
| Package Manager | Behavior |
|-----------------|----------|
| dnf/yum/zypper  | Update metadata regularly by default, and checked when installing any package |
| pacman | We run it with -Sy so metadata is always updated |
cherry-picked from: apernet/tcp-brutal@efcc08b936dec95a7f4645bb82d501784b21b156
Reference: apernet/tcp-brutal#16
This PR is created as the "Protect master" policy is enforced on this repository.
> chore(scripts): run apt update on apt based distro

- scripts/install_server.sh
WorkingDirectory=~ requires systemd v227 or later, which is released on Oct 2015, only CentOS 7 use an earlier version actually.
ref: https://github.com/apernet/hysteria/issues/1091#issuecomment-2119186022
ref: systemd/systemd@5f5d8eab1f2f5f5e088bc301533b3e4636de96c7
> fix(scripts): WorkingDirectory on CentOS 7

- app/internal/http/server.go
Go's resp.Write() adds a "Content-Length: 0" header and it seems that ffmpeg doesn't like this and immediately closes the proxy connection.
close: #1109
> fix(client/http): ffmpeg not works with proxy

- app/cmd/client.go
When calling `func (c *clientConfig) URI() string` to generate hysteria2 share links, the **Auth** is escaped. But when calling `func (c *clientConfig) parseURI() bool` to parse hysteria2 share links, the **Auth** is NOT unescaped.
> fix escaped auth

- scripts/install_server.sh
`chcon` is widely available in coreutils, even if the system doesn't support selinux.
> fix(scripts): detect selinux with getenforce

- app/cmd/server.go
- app/cmd/server_test.go
- app/cmd/server_test.yaml
- app/internal/utils/certloader.go
- app/internal/utils/certloader_test.go
- app/internal/utils/certloader_test_gencert.py
- app/internal/utils/certloader_test_tlsclient.py
- app/internal/utils/testcerts/.gitignore
- requirements.txt
close: #1189
This PR refactored the local certificate load routine with caching support (based on mtime) and added the following option to the server config file:
```yaml
tls:
sniGuard: disable | strict | dns-san
```
+ `disable`: Old behavior. Reply with the certificate and complete the TLS handshake regardless of the SNI.
+ `strict`: The behavior of caddy. The SNI in ClientHello or the server-side IP in the request must match one of the certificate's SANs, otherwise the handshake will be aborted and the connection will be terminated.
+ `dns-san`: Use the old behavior if the configured certificate doesn't have a valid DNS SAN, otherwise same as strict. This option is the default and was introduced to ensure compatibility with those poorly generated self-signed certificates.
> feat: local cert loader & sni guard

- core/internal/integration_tests/hook_test.go
- core/server/udp.go
- core/server/udp_test.go
ref: https://github.com/apernet/hysteria/discussions/1204#discussioncomment-10702442
This PR rewrites `udpSessionEntry` and `udpSessionManager.feed()` to ensure sniffer is called with reassembled first packet.
> fix: quic sniff not work if udp msg fragmentated

- app/cmd/server.go
Check the URL scheme of `masquerade.proxy.url` when parsing server config and fail fast if it is not `"http"` or `"https"`.
ref: #1227
The user assigned the URL with a naked hostname and got no errors until the request was handled.
> fix: check the URL scheme of `masquerade.proxy.url` in server config

- app/cmd/share.go
Useful for third-party scripts/clients that just want to generate the sharing URI without starting the client.
> feat: share subcommand

- extras/utils/portunion.go
- extras/utils/portunion_test.go
fix: #1240 
Maybe also have a look at `PortUnion.Normalize()`?
> fix: infinite loop in PortUnion.Ports() when port range contains 65535

- app/cmd/root.go
- hyperbole.py
- scripts/install_server.sh
Sample output:
```
░█░█░█░█░█▀▀░▀█▀░█▀▀░█▀▄░▀█▀░█▀█░░░▀▀▄
░█▀█░░█░░▀▀█░░█░░█▀▀░█▀▄░░█░░█▀█░░░▄▀░
░▀░▀░░▀░░▀▀▀░░▀░░▀▀▀░▀░▀░▀▀▀░▀░▀░░░▀▀▀
a powerful, lightning fast and censorship resistant proxy
Aperture Internet Laboratory <https://github.com/apernet>
Version:        v2.5.2-8-ga2c7b8f
BuildDate:      2024-11-04T19:57:56Z
BuildType:      dev-run
Toolchain:      go1.23.2 windows/amd64
CommitHash:     a2c7b8fd198dc6d8240d60b7561158f3c3f7dc74
Platform:       windows
Architecture:   amd64
LibVersion:     v0.47.1-0.20241004180137-a80d14e2080d
```
> feat: add toolchain & quic-go to version info

- app/cmd/root.go
close: #1271
A key that also contains "Version" broke the version parsing of some third-party clients.
```
./hyperbole.py run version
░█░█░█░█░█▀▀░▀█▀░█▀▀░█▀▄░▀█▀░█▀█░░░▀▀▄
░█▀█░░█░░▀▀█░░█░░█▀▀░█▀▄░░█░░█▀█░░░▄▀░
░▀░▀░░▀░░▀▀▀░░▀░░▀▀▀░▀░▀░▀▀▀░▀░▀░░░▀▀▀
a powerful, lightning fast and censorship resistant proxy
Aperture Internet Laboratory <https://github.com/apernet>
Version:        v2.6.0-5-g400fed3
BuildDate:      2024-12-11T09:09:43Z
BuildType:      dev-run
Toolchain:      go1.23.2 linux/amd64
CommitHash:     400fed3bd607d5f529487aa07d7f4d630c802ae4
Platform:       linux
Architecture:   amd64
Libraries:      quic-go=v0.48.2-0.20241104191913-cb103fcecfe7
```
> chore(version): rename LibVersion to Libraries

- app/internal/tun/check_ipv6_others.go
- app/internal/tun/check_ipv6_unix.go
- app/internal/tun/check_ipv6_windows.go
- app/internal/tun/server.go
> fix: tun failed on linux when ipv6.disable=1

- app/cmd/server.go
- extras/auth/userpass.go
- extras/auth/userpass_test.go
close: #1297
Just a workaround for "uppercase usernames do not work".
Usernames in different cases (like "Gawr" and "gawR") will now conflict.
However, such conflicts are still not reported as errors, which seems impossible while we are still using viper.
External authentication using HTTP or command is not affected by this PR.
We also need to update docs for userpass.
> Make username of userpass case insensitive

- app/cmd/client.go
Close: #1355
Since we already have the `share` subcommand, this feature is unnecessary for the `client` subcommand.
This commit disables printing the share URI after the client starts, but keeps this behavior for users who specified the `--qr` flag (who may still rely on it) and shows a deprecation warning.
> fix(client): remove share uri in log

- app/cmd/client.go
A malicious actor is capable of intercepting QUIC traffic between the client
and the server.
The attack requires to use certificate pinning with CA-issued certificates. The hysteria client tries to match the pinned hash against every single cert in the certchain. If the client is misconfigured to pin the hash of the CA root cert instead of the end-entity cert this will leak hysteria password in a MITM attack. The server must be configured with a cert-chain, not just an end-entity certificate. Setting sniGuard: disable in the server config allows the attacker to also to analyze the traffic inside the tunnel.
> Fix the MITM vulnerability
